# Generated by Django 2.1 on 2020-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bio',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_title',
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
